---
apiVersion: v1
kind: Namespace
metadata:
  name: tan-dev
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-test
  namespace: tan-dev
spec:
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx-test
        image: alpine
        command: ["/bin/sh", "-c"]
        args:
        - tail -f /dev/null
        # ports:
        # - containerPort: 81
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 300Mi
        #   limits:
        #     cpu: 200m
        #     memory: 400Mi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-test
#   labels:
#     app: nginx-test
#   namespace: tan-dev
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: http
#   selector:
#     app: nginx-test
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: nginx-test
#   labels:
#     app: nginx-test
#   namespace: tan-dev
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#     ingress.kubernetes.io/configuration-snippet: |
#       more_set_headers "Request-Id: $request_id";
#     ingress.kubernetes.io/session-cookie-name: "suker200"
#     ingress.kubernetes.io/session-cookie-hash: "md5"
#     ingress.kubernetes.io/affinity: "cookie"
#     ingress.kubernetes.io/force-ssl-redirect: "true" # for Offload TLS from cloud provider
# spec:
#   rules:
#     - host: abc.suker200.com
#       http:
#         paths:
#           - path: /
#             backend:
#               serviceName: nginx-test
#               servicePort: http